### ISSUE TITLE
lumimqtt crashes

### ISSUE THREAD

**Issue by definitio** [openlumi/lumimqtt#31]
```
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]: Traceback (most recent call last):
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/bin/lumimqtt", line 8, in <module>
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     sys.exit(main())
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/lumimqtt/__main__.py", line 88, in main
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     loop.run_until_complete(server.start())
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/lumimqtt/lumimqtt.py", line 106, in start
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     t.result()
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/lumimqtt/lumimqtt.py", line 356, in _periodic_publish
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     await self._publish_sensor(sensor, value)
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/lumimqtt/lumimqtt.py", line 381, in _publish_sensor
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     await self._client.publish(
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/aio_mqtt/client.py", line 291, in publish
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     await self._send_publish(message, packet_id)
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:   File "/usr/lib/python3.9/site-packages/aio_mqtt/client.py", line 612, in _send_publish
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]:     packet.extend(struct.pack('!H', packet_id))
Wed Jun  1 18:32:30 2022 daemon.err lumimqtt[20937]: struct.error: 'H' format requires 0 <= number <= 65535
```

**Comment by devbis** [comment]
Thank you! It is fixed in version 1.0.15.
