### ISSUE TITLE
lumimqtt not starting

### ISSUE THREAD

**Issue by kuenkin** [openlumi/lumimqtt#40]
Hello,
 I'm trying to install lumimqtt on a ZHWG11LM with openwrt 21.02.7 . But it doesn't start:
```root@Altavoz_Aqara_nowd:/tmp# lumimqtt
Traceback (most recent call last):
  File "/usr/bin/lumimqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/lumimqtt/__main__.py", line 105, in main
    aio.run(amain())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
  File "/usr/lib/python3.9/site-packages/lumimqtt/__main__.py", line 86, in amain
    for device in devices(
  File "/usr/lib/python3.9/site-packages/lumimqtt/platform.py", line 92, in devices
    return sensors(binary_sensors) + buttons() + lights() + \
  File "/usr/lib/python3.9/site-packages/lumimqtt/platform.py", line 75, in lights
    lights_.append(Light(name=name, devices=device_dirs, topic=name))
  File "/usr/lib/python3.9/site-packages/lumimqtt/light.py", line 39, in __init__
    self.red = LED(f'{name}_red', devices['red'])
  File "/usr/lib/python3.9/site-packages/lumimqtt/light.py", line 21, in __init__
    self.brightness = int(self.read_raw(self.device_file))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' ```

**Comment by kuenkin** [comment]
Ok. It seems to be related to the special installation this unit has, with no watchdog: [Nowatchdog](https://github.com/openlumi/openlumi.github.io/issues/49) , as I tried in other one I have and I can install it without problems.

**Comment by devbis** [comment]
You can try to build you own DTB for the device playing with watchdog parameters. Or try a newer version of Openwrt
